// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLR9oZ0QX1U3pVG62ch3ycGAAxIdh5yac',
    appId: '1:426114322247:web:bed4f34c042f48fe39c662',
    messagingSenderId: '426114322247',
    projectId: 'sortb-32d2d',
    authDomain: 'sortb-32d2d.firebaseapp.com',
    storageBucket: 'sortb-32d2d.appspot.com',
    measurementId: 'G-KBEFCG3E8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXDHn6e0SM0b11TDCMIR0vJ1mWjm5g5tU',
    appId: '1:426114322247:android:9a87f3227b09557439c662',
    messagingSenderId: '426114322247',
    projectId: 'sortb-32d2d',
    storageBucket: 'sortb-32d2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWBCSIdu2jHJ1QxP3ZlDxVXrRWK_w4kUs',
    appId: '1:426114322247:ios:e281c2ac48db722939c662',
    messagingSenderId: '426114322247',
    projectId: 'sortb-32d2d',
    storageBucket: 'sortb-32d2d.appspot.com',
    iosBundleId: 'com.example.sortedbraintask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWBCSIdu2jHJ1QxP3ZlDxVXrRWK_w4kUs',
    appId: '1:426114322247:ios:e281c2ac48db722939c662',
    messagingSenderId: '426114322247',
    projectId: 'sortb-32d2d',
    storageBucket: 'sortb-32d2d.appspot.com',
    iosBundleId: 'com.example.sortedbraintask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLR9oZ0QX1U3pVG62ch3ycGAAxIdh5yac',
    appId: '1:426114322247:web:47b96745f41ad7dc39c662',
    messagingSenderId: '426114322247',
    projectId: 'sortb-32d2d',
    authDomain: 'sortb-32d2d.firebaseapp.com',
    storageBucket: 'sortb-32d2d.appspot.com',
    measurementId: 'G-WQ218CBFVZ',
  );
}
